name: New Feature Launch
description: Submit a request for coordinating a new feature launch
title: "[New Feature Launch]: "
body:
  - type: markdown
    attributes:
      value: >
        Thanks for submitting a request for a new feature launch! Please fill in the details 
        below so that we can process it.

        Note that new feature launches should follow 
        [these steps](https://github.com/oppia/oppia/wiki/Launching-new-features#how-to-use-feature-flags).
  - type: dropdown
    id: product-id
    attributes:
      label: Product
      description: Which platform/team owns this feature?
      options:
        - Web (LaCE)
        - Web (Contributor Dashboard)
        - Android
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Brief description of the feature. Include links to PRD and TDD, where possible.
    validations:
      required: true
  - type: input
    id: pre-launch-review-doc-link
    attributes:
      label: Link to the Pre-Launch Review Doc for this feature
      description: >
        This should be a document that follows
        [this template](https://docs.google.com/document/d/1ibQC9t1jnOg-o1lrHEM3QEXeF4eSqAiPhs2lD2iCpy4/edit?tab=t.4t336fwwj9ly).
    validations:
      required: true
  - type: input
    id: drive-folder-link
    attributes:
      label: Link to the ProdOps Drive folder for this feature
      description: >
        This should be a subfolder of the [ProdOps Feature Launch folder](https://drive.google.com/drive/folders/10TW7dUApMoBW4mhEh_JFuQxldWNudPv0). 
        Ask a ProdOps lead or Tech Lead to make one for you if needed. The folder should include the pre-launch doc above,
        as well as any related documents (PRD, TDD, CUJs, etc.).
    validations:
      required: true
  - type: dropdown
    id: expected-code-complete-date
    attributes:
      label: Expected code-complete date
      description: This should include implementation of any analytics events noted in the PRD.
      options:
        - 2025 Q4
        - 2026 Q1
        - 2026 Q2
        - 2026 Q3
        - 2026 Q4
        - 2027 Q1
        - 2027 Q2
    validations:
      required: true
  - type: input
    id: developer-id
    attributes:
      label: Developer point-of-contact
      description: GitHub username of the primary feature developer
    validations:
      required: true
  - type: checkboxes
    id: responsible-tls
    attributes:
      label: Dev Leads
      description: Who are the responsible dev leads for this feature?
      options:
        - label: kevintab95
        - label: U8NWXD
        - label: BenHenning
        - label: adhiamboperes
        - label: HardikGoyal2003
        - label: mon4our
        - label: chris7716
        - label: masterboy376
    validations:
      required: true
  - type: checkboxes
    id: testing-roles
    attributes:
      label: Required roles for testing
      description: Which role permissions are needed to test this feature?
      options:
        - label: Curriculum admin
        - label: Topic manager
        - label: Question admin/coordinator
        - label: Question reviewer
        - label: Question submitter
        - label: Translation admin/coordinator
        - label: Translation reviewer
        - label: Translation submitter
        - label: Voiceover admin
        - label: Blog admin
        - label: Blog post editor
        - label: None of the above
    validations:
      required: true
  - type: input
    id: feature-flag-name
    attributes:
      label: Feature flag name
      description: Name of the feature flag that needs to be flipped to enable this feature
    validations:
      required: true
  - type: input
    id: feature-flag-min-version
    attributes:
      label: (Android only) Minimum supported Android version
      description: Specify the minimum Android version to enable the feature flag for
    validations:
      required: false
  - type: input
    id: test-stage-PR
    attributes:
      label: Link to the PR which moved the flag to the TEST feature stage
      description: >
        To be eligible for launch, your feature flag must be in the TEST stage.
        See guidance [here](https://github.com/oppia/oppia/wiki/Launching-new-features#how-to-use-feature-flags).
    validations:
      required: false
  - type: input
    id: google-space-link
    attributes:
      label: Link to the launch command channel for this feature.
      description: The tech lead will add this when handing off to ProdOps.
    validations:
      required: false
  - type: textarea
    id: any-other-info
    attributes:
      label: (Optional) Is there anything else you would like the ProdOps team to know?
      description: >
        For example, anything in particular that you would like feedback on during testing. The ProdOps
        team will include this request when corresponding with the QA team.
    validations:
      required: false
  - type: textarea
    id: instructions-for-prodops
    attributes:
      label: Instructions for Dev Leads, Prod Ops and QA Teams
      description: Please leave this section as-is.
      value: |
        ------

        When you are assigned to this issue, please do the following. Tick each
        checkbox item as you complete each step:

        #### Tech-lead prep (to be done by a tech lead)
        - [ ] Ensure that this issue is filed correctly. Ask for any missing info if needed.
        - [ ] Confirm that the Drive folder is in the [ProdOps Feature Launch folder](https://drive.google.com/drive/folders/10TW7dUApMoBW4mhEh_JFuQxldWNudPv0).
        - [ ] Confirm that the Drive folder contains the pre-launch review doc, PRD, and TDD (these should be the actual docs, not just shortcut links to them).
        - [ ] Ask the developer and the relevant dev team leads to subscribe to **this issue thread** for updates, and ensure that they've done so. (You should also subscribe to it for the same reason.)
        - [ ] Ask the developer and the relevant dev team leads to subscribe to [comment/edit notifications](https://support.google.com/docs/answer/91588?hl=en&co=GENIE.Platform%3DDesktop) on the **pre-launch review doc** for updates, and ensure that they've done so. (You should also subscribe to it for the same reason.)
        - [ ] Ensure that the "Information for Testers" and "Information for Server Admins" pages of the pre-launch review doc are fully filled in.        
        - [ ] Ensure that the CUJs in the spreadsheet relating to this feature are updated. If any behaviour is hidden behind a flag, there should be a "Current" row and a separate row for the flag-hidden behaviour.
        - [ ] Verify that all the above CUJs are fully covered by acceptance tests, and that the implemented acceptance tests in the codebase match the ones documented in the spreadsheet.
        - [ ] If the feature launch will include manual steps (in addition to deploying to PROD and turning the flag on), create a **tech launch plan** with all the steps needed, similar to [this one](https://docs.google.com/document/d/1AmECWsG8KQcYDtB91725MHfN0G6hp86HEiV_okXspNg/edit?tab=t.0). Ensure that it is added to the Drive folder. This should consider any migrations or data upgrades that need to happen, as well as any launch-time changes that are needed for reliabilty, deployability, performance, scalability, and stability.
        - [ ] Verify that the "test stage" PR has been merged (see the "Link to the PR which moved the flag to the TEST feature stage" field), and that it actually moves the feature flag to the TEST stage.

        #### Tech-lead verification (to be done by the same tech lead)
        - [ ] Once the "test stage" PR has been merged, deploy it to the backup-server.
        - [ ] Enable the feature flag on the backup-server.
        - [ ] Complete any steps in the tech launch plan (if one exists) on the backup-server.
        - [ ] Verify that the feature's CUJs actually work technically on the backup-server (with the flag enabled). Clarify any CUJs that aren't clear with the developer.
        - [ ] Set up a Google Space group chat for this feature launch. Title it "[Launch] Name_Of_Feature" (where Name_Of_Feature is replaced by the name of the feature you're launching).
        - [ ] Invite the following people to the launch group chat: (a) the developer of the feature, (b) the relevant dev leads, (c) the ProdOps assignee, (d) the ProdOps leads, (e) any folks in UXD/UXR who were involved in the feature's design, (f) the QA assignee, (g) the QA leads, (h) the Marketing assignee, and (i) the Marketing leads.
        - [ ] Click on the "Board" icon in the Google Space, and add the following resources in this order: (a) TDD, (b) PRD, (c) Drive folder, (d) Launch Checklist (GitHub), (e) Pre-Launch Review Doc. (The resources will then appear in reverse order, so that the pre-launch review doc is at the top.)
        - [ ] Send a message to `@all` to introduce the group chat and ask everyone in it to subscribe to the space with "Notifications" set to "All". Explain that the launch chat is where all communication about the launch will happen, and that the launch checklist on GitHub must be kept up-to-date. Provide a link to the GitHub launch checklist.
        - [ ] Ask everyone in the launch chat (ProdOps, QA) to subscribe to [comment/edit notifications](https://support.google.com/docs/answer/91588?hl=en&co=GENIE.Platform%3DDesktop) on the **pre-launch review doc** for updates.
        - [ ] Ensure that the ProdOps assignee has the correct permissions on the backup-server to do a dry-run of the feature.
        - [ ] Hand off this issue to the ProdOps team (deassign yourself and tag/add the correct assignee from ProdOps). (Only mark this step as complete once the **ProdOps assignee** has acknowledged the handoff.)

        #### Preparation and Dry-Run (ProdOps team)
        - [ ] Verify that the Marketing team's [tracker](https://docs.google.com/spreadsheets/d/1zkucuPbuFp9gzJXcWKjoZCqwDTT24xY1ufSX7ku9JAo/edit?gid=0#gid=0) has a sheet for this product launch.
        - [ ] Send an email to qa-leads@ to let them know that the feature is coming soon (subject to passing the ProdOps dry-run).
        - [ ] [LATER, once analytics pipeline is set up] Set up the Looker Studio dashboard for the feature, and supplement it with metrics obtained using BigQuery queries, as needed.
        - [ ] [LATER, once analytics pipeline is set up] Add a link to the backup-server Looker Studio dashboard in the instructions for testers.
        - [ ] Do a full run-through of the feature, and make updates to clarify the CUJ descriptions as needed. Then, post a new comment to this thread with the testing report, and cc the developer and relevant dev team leads. Ensure that any bugs found during this process are filed and assigned to the developer. If you see design issues, it's fine to loop in the design team. If issues were discovered in the run-through, repeat the above as needed until there are no more issues. (Only mark this step as complete once that stage is reached -- at this point, ProdOps is saying "I'm happy with the feature, it can go to full QA.")
        - [ ] [LATER, once analytics pipeline is set up] Verify that events from the testing were correctly recorded on the Looker Studio dashboard.

        #### Full feature testing (ProdOps and QA teams)
        - [ ] Send QA team (qa-team AT oppia DOT org) an email that a new feature is ready for testing. Send them the pre-launch doc (with CUJs) and request the list of tester usernames.
        - [ ] Ask the tech leads to provide the necessary permissions (see "Required roles for testing", above) to the tester usernames on the backup-server.
        - [ ] Ask QA leads to (a) start the feature testing process, (b) send updates to the group chat after each testing cycle, and (c) send a final update once they've confirmed that the full feature is working properly and is good to launch. If there are bugs found in the testing, they should inform the developer, who should fix the issues and ask for a re-test. This continues until all issues have been fixed. (While this is happening, ProdOps should periodically check the Looker Studio dashboard to verify that metrics are being correctly recorded during feature testing, and adjust the metrics, if needed, to make them more useful.) (Note: Only mark this step as complete **when the QA leads have notified the group chat that testing is complete**.)
        - [ ] Ask the tech leads to move the feature to PROD stage, and add a link to the PR here once it is merged: ______. (Only mark this step as complete once the **tech leads** have done this.)
        - [ ] Perform a final Product review. Product should review the state of QA findings, including whether any bugs still exist, and look at the feature again if a lot of changes have been made. They should also understand any caveats (e.g. if anything has been disabled due to quality issues, etc.). They should also decide (in collaboration with the Campaign Strategy and UXR teams) whether the project needs a "trusted tester" phase.
        - [ ] If the decision is made to include a "trusted tester" phase, run through this with the UXR/Marketing teams following the guidance in the Product/Marketing Communication Process document. (Only mark this step as complete when the "trusted tester" phase is complete, or if there is no "trusted tester" phase.)
        - [ ] Formally greenlight the launch. (Only mark this step as complete when ProdOps has made the decision to greenlight.)

        #### Rollout (ProdOps team)
        - [ ] Agree on launch date with Marketing team and tech leads, and document it here.
             - [ ] **Deployment date of binary** (with the flag enable-able in PROD mode): _________.
             - [ ] **Date for completing all marketing collateral**: _______.
             - [ ] **Launch date to users** (must be after the above): _______.
        - [ ] Turn on the feature flag for just the PM.
        - [ ] PM verifies that the feature works correctly.
        - [ ] [LATER, once analytics pipeline is set up] Check the ProdOps "CUJ health" analytics dashboard to verify that the new dashboards for this feature have been included in it.
        - [ ] Work with the server admins team to flip the feature flag per the rollout schedule before the launch date, and confirm that the feature works in production. (Do partial rollout if desired, to make sure usage doesn't drop / support requests don't spike / system health is good.)
        - [ ] Once the feature is actually launched to all users:
             - [ ] Send out a congratulatory launch email, crediting all the folks involved in the launch. Show some pictures!
             - [ ] Update the rows for this feature in the master CUJ document to have a status of "Current" (rather than being gated behind a flag).
        - [ ] Monitor post-launch metrics through the feature's Looker Studio dashboard (constructed above), filed [GitHub issues](https://github.com/oppia/oppia/issues), and [Google Groups forum](https://groups.google.com/g/oppia).
        - [ ] 2 weeks after launch, compile a [post-launch report](https://docs.google.com/document/d/1DifFAe3oRzjmVPh2fEllfAky4n0QMAXVQc3Y580qkr8/edit) and schedule a post-launch review with everyone on the command channel (design, developers, marketing, QA).
        - [ ] Ask the tech leads to remove the feature flag. **Link to PR that removes the flag: _____.**
        - [ ] Close this bug. This concludes the feature launch, congratulations! 🎉
    validations:
      required: true
