name: New Feature Launch
description: Submit a request for coordinating a new feature launch
title: "[New Feature Launch]: "
body:
  - type: markdown
    attributes:
      value: >
        Thanks for submitting a request for a new feature launch! Please fill in the details 
        below so that we can process it.

        Note that new feature launches should follow 
        [these steps](https://github.com/oppia/oppia/wiki/Launching-new-features#how-to-use-feature-flags).
  - type: dropdown
    id: product-id
    attributes:
      label: Product
      description: Which platform/team owns this feature?
      options:
        - Web (LaCE)
        - Web (Contributor Dashboard)
        - Android
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Brief description of the feature. Include links to PRD and TDD.
    validations:
      required: true
  - type: dropdown
    id: expected-code-complete-date
    attributes:
      label: Expected code-complete date
      description: This should include implementation of any analytics events noted in the PRD.
      options:
        - 2025 Q2
        - 2025 Q3
        - 2025 Q4
        - 2026 Q1
        - 2026 Q2
        - 2026 Q3
        - 2026 Q4
    validations:
      required: true
  - type: input
    id: developer-id
    attributes:
      label: Developer point-of-contact
      description: GitHub username of the primary feature developer
    validations:
      required: true
  - type: input
    id: cujs-link
    attributes:
      label: Link to the spreadsheet containing the critical user journeys for this feature
      description: >
        The spreadsheet should be formatted similarly to this
        [acceptance test matrix](https://docs.google.com/spreadsheets/d/1O8EHiSAGrG0yoNUBz9E4DIwKNS8Rfsv_ffC4k1WK5jc/edit?gid=1275148408#gid=1275148408).
        In other words, the user journeys should be grouped by user type, and clearly laid out with steps and expectations.
    validations:
      required: true
  - type: checkboxes
    id: testing-roles
    attributes:
      label: Required roles for testing
      description: Which role permissions are needed to test this feature?
      options:
        - label: Curriculum admin
        - label: Topic manager
        - label: Question admin/coordinator
        - label: Question reviewer
        - label: Question submitter
        - label: Translation admin/coordinator
        - label: Translation reviewer
        - label: Translation submitter
        - label: Voiceover admin
        - label: Blog admin
        - label: Blog post editor
        - label: None of the above
    validations:
      required: true
  - type: input
    id: test-stage-PR
    attributes:
      label: Link to the PR which moved the flag to the TEST feature stage
      description: >
        To be eligible for feature testing, your feature flag must be in the TEST stage.
        See guidance [here](https://github.com/oppia/oppia/wiki/Launching-new-features#how-to-use-feature-flags).
    validations:
      required: true  
  - type: input
    id: url-path
    attributes:
      label: URL path from which to access the feature
      description: >
        Which initial URL path is this feature accessed from? Note
        that it should start with a '/', e.g. '/learn/math`.
    validations:
      required: true
  - type: input
    id: feature-flag-name
    attributes:
      label: Feature flag name
      description: Name of the feature flag that needs to be flipped to enable this feature
    validations:
      required: true
  - type: input
    id: feature-flag-min-version
    attributes:
      label: (Android only) Minimum supported Android version
      description: Specify the minimum Android version to enable the feature flag for
    validations:
      required: false
  - type: textarea
    id: any-other-info
    attributes:
      label: (Optional) Is there anything else you would like the testing team to know?
      description: >
        For example, anything in particular that you would like feedback on. The ProdOps
        team will include this request when corresponding with the QA team.
    validations:
      required: false
  - type: textarea
    id: instructions-for-prodops
    attributes:
      label: Instructions for ProdOps Team
      description: Please leave this section as-is.
      value: |
        When you are assigned to this issue, please do the following. Tick each
        checkbox item as you complete each step:

        **Preparation**

        - [ ] Work with the developer to narrow the code-complete date above to a specific day.
        - [ ] Ensure that the PRD, TDD, CUJs, permissions and starting URL path are provided.
        - [ ] Ensure that the "test stage" PR and feature flag name are provided, and that the
              "test stage" PR actually moves the feature flag to the TEST stage.
        - [ ] Ensure that the Google Drive folder for this feature has been correctly set up
              and contains the necessary documents (e.g. pre-launch review template).
        - [ ] Ask the developer and the relevant dev team leads to subscribe to this
              issue thread; ensure that they have done so.
        - [ ] Once the "test stage" PR has been merged, ask the server admins to schedule a 
              backup-server deployment of that PR.
        - [ ] Ask Sean to provide your username on that server with the necessary permissions.

        **Dry-run**

        - [ ] Do a run-through of the feature and post a new comment to this thread with the
              testing report. Add a comment to this issue thread with a link to the testing report.
        - [ ] If issues were discovered in the run-through, repeat the above as needed until there
              are no more issues. (Only mark this step as complete once that stage is reached.)
        - [ ] Set up the Looker Studio dashboard for this feature and verify that it records events
              correctly.

        **Full feature testing**

        - [ ] Set up a Google Space for this feature launch and invite all relevant parties
              (design, developer, QA, campaign strategy team members + leads).
        - [ ] Give the QA team a heads-up that a new feature will be coming to test soon. Send them
              the CUJs and request the list of testers.
        - [ ] Ask Sean to provide the tester usernames on the backup server with the necessary
              permissions.
        - [ ] Run the feature testing process with the QA team and send a report to the developer
              and the dev leads. Add a comment to this issue thread with a link to this report.
        - [ ] If issues were discovered in the testing, repeat the above as needed until there are
              no more issues. (Only mark this step as complete once the feature passes testing.)
        - [ ] Ask the developer to move their flag to PROD stage. Link to the PR here once it is
              merged: ______.

        **Rollout**

        - [ ] Agree on launch date with Marketing team and document it here. **Launch date**: ______.
        - [ ] Monitor post-launch metrics through the feature's Looker Studio dashboard (constructed above).
        - [ ] Monitor post-launch feedback through [GitHub](https://github.com/oppia/oppia/issues) issues,
              filed and [Google Groups forum](https://groups.google.com/g/oppia).
        - [ ] 2 weeks after launch, compile a post-launch report and schedule a debrief with everyone on
              the command channel (design, developers, marketing, QA).
        - [ ] Close this bug. This concludes the feature launch, congratulations! 🎉
    validations:
      required: true
