name: Documentation/Admin Task
description: Submit a request for improving team documentation (or doing other admin tasks)
title: "[Documentation/Admin]: "
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Description of the task
    validations:
      required: true
  - type: textarea
    id: required-result
    attributes:
      label: When should this issue be considered complete?
    validations:
      required: true
  - type: textarea
    id: other-context
    attributes:
      label: Any other relevant context/info
    validations:
      required: false
